In [99]:
#подгружаем библиотеки
import pandas as pd
import numpy as np
from sklearn. preprocessing import OneHotEncoder
import category_encoders as ce
from scipy.stats import shapiro
from scipy.stats import ttest_ind
from scipy.stats import mannwhitneyu
import scipy.stats as stats

In [ ]:
#таблица с прайсом
item_prices = pd.read_csv("item_prices.csv")
item_prices.head()

   item_id  item_price
0      338        1501
1       74         647
2     7696         825
3      866         875
4     5876         804

In [ ]:
sample_a = pd.read_csv("sample_a.csv")
sample_a.head()

   user_id  item_id  action_id
0    84636      360          1
1    21217     9635          1
2    13445     8590          1
3    38450     5585          1
4    14160     2383          0

In [102]:
#проверяем наличие дубликатов
duplicateRows_a = sample_a[sample_a.duplicated()]
print('Количество дубликатов в sample_a: {}'.format(len(duplicateRows_a)))

Количество дубликатов в sample_a: 0

In [103]:
#создаем отдельную таблицу со значением action_id = 2
sample_a_2 = sample_a.loc[sample_a['action_id'] == 2]
a_action_2 = set(sample_a_2['item_id'])
#создаем отдельную таблицу со значением action_id = 1
sample_a_1 = sample_a.loc[sample_a['action_id'] == 1]
a_action_1 = set(sample_a_1['item_id'])
#создаем отдельную таблицу со значением action_id = 0
sample_a_0 = sample_a.loc[sample_a['action_id'] == 0]
a_action_0 = set(sample_a_1['item_id'])

In [104]:
a_dubl21 = a_action_2 - a_action_1
print('Количество покупок без просмотра: {}'.format(len(a_dubl21)))
a_dubl01 = a_action_0 - a_action_1
print('Количество кликов без просмотра: {}'.format(len(a_dubl01)))

Количество покупок без просмотра: 0
Количество кликов без просмотра: 0

Дублей и случаев с покупкой и кликами в дата-сете simple_a без просмотра не выявлено

Рассмотрим sample_b

In [ ]:
sample_b = pd.read_csv("sample_b.csv")

In [106]:
#проверяем наличие дубликатов
duplicateRows_b = sample_b[sample_b.duplicated()]
print('Количество дубликатов в sample_b: {}'.format(len(duplicateRows_b)))

Количество дубликатов в sample_b: 0

In [107]:
#создаем отдельную таблицу со значением action_id = 2
sample_b_2 = sample_b.loc[sample_b['action_id'] == 2]
b_action_2 = set(sample_b_2['item_id'])
#создаем отдельную таблицу со значением action_id = 1
sample_b_1 = sample_b.loc[sample_b['action_id'] == 1]
b_action_1 = set(sample_b_1['item_id'])
#создаем отдельную таблицу со значением action_id = 0
sample_b_0 = sample_b.loc[sample_b['action_id'] == 0]
b_action_0 = set(sample_b_0['item_id'])

In [108]:
b_dubl21 = b_action_2 - b_action_1
print('Количество покупок без просмотра: {}'.format(len(b_dubl21)))
b_dubl01 = b_action_0 - b_action_1
print('Количество кликов без просмотра: {}'.format(len(b_dubl01)))

Количество покупок без просмотра: 0
Количество кликов без просмотра: 0

Дублей и случаев с покупкой и кликами в дата-сете simple_b без просмотра не выявлено

Рассмотрим дата-сет simple_c

In [ ]:
sample_c = pd.read_csv("sample_c.csv")

In [110]:
#проверяем наличие дубликатов
duplicateRows_c = sample_c[sample_c.duplicated()]
print('Количество дубликатов в sample_c: {}'.format(len(duplicateRows_c)))

Количество дубликатов в sample_c: 0

In [111]:
#создаем отдельную таблицу со значением action_id = 2
sample_c_2 = sample_c.loc[sample_c['action_id'] == 2]
c_action_2 = set(sample_c_2['item_id'])
#создаем отдельную таблицу со значением action_id = 1
sample_c_1 = sample_c.loc[sample_c['action_id'] == 1]
c_action_1 = set(sample_c_1['item_id'])
#создаем отдельную таблицу со значением action_id = 0
sample_c_0 = sample_c.loc[sample_c['action_id'] == 0]
c_action_0 = set(sample_c_0['item_id'])

In [112]:
c_dubl21 = c_action_2 - c_action_1
print('Количество покупок без просмотра: {}'.format(len(c_dubl21)))
c_dubl01 = c_action_0 - c_action_1
print('Количество кликов без просмотра: {}'.format(len(c_dubl01)))

Количество покупок без просмотра: 0
Количество кликов без просмотра: 0

Дублей и случаев с покупкой и кликами в дата-сете simple_c без просмотра не выявлено

Создадим метрики для дата-сета sample_a

In [113]:
sample_a_prices = pd.merge(sample_a, item_prices, on=['item_id'], how='left')
sample_a_prices.head()

   user_id  item_id  action_id  item_price
0    84636      360          1        1896
1    21217     9635          1        1699
2    13445     8590          1         846
3    38450     5585          1        1556
4    14160     2383          0        1956

In [114]:
#проведем горячее кодирование признака action_id
encoder = ce.OneHotEncoder(cols=['action_id'], use_cat_names=True) # указываем столбец для кодирования
type_bin = encoder.fit_transform(sample_a_prices['action_id'])
sample_a_prices = pd.concat([sample_a_prices, type_bin], axis=1)
sample_a_prices.head()

,user_id,item_id,action_id,item_price,action_id_1.0,action_id_0.0,action_id_2.0
0,84636,360,1,1896,1,0,0
1,21217,9635,1,1699,1,0,0
2,13445,8590,1,846,1,0,0
3,38450,5585,1,1556,1,0,0
4,14160,2383,0,1956,0,1,0

In [115]:
#создадим сводную таблицу по признаку 'item_id'
a_metrics = sample_a_prices.groupby('item_id')[['action_id_1.0', 'action_id_0.0', 'action_id_2.0']].sum()
a_metrics = pd.merge(a_metrics, item_prices, on=['item_id'], how='left')

In [116]:
#вычислим метрики
a_metrics['ctr'] = a_metrics['action_id_0.0'] / a_metrics['action_id_1.0']
a_metrics['purchase_rate'] = a_metrics['action_id_2.0'] / a_metrics['action_id_1.0']
a_metrics['gmv'] = a_metrics['action_id_2.0'] * a_metrics['item_price']
a_metrics.head()

,item_id,action_id_1.0,action_id_0.0,action_id_2.0,item_price,ctr,purchase_rate,gmv
0,21,996,196,50,452,0.196787,0.050201,22600
1,36,996,181,45,282,0.181727,0.045181,12690
2,39,996,205,44,1746,0.205823,0.044177,76824
3,50,996,205,59,871,0.205823,0.059237,51389
4,64,996,200,61,1479,0.200803,0.061245,90219

Создадим метрики для sample_b

In [117]:
sample_b_prices = pd.merge(sample_b, item_prices, on=['item_id'], how='left')
sample_b_prices.head()

   user_id  item_id  action_id  item_price
0   118375     4105          1         536
1   107569     8204          1        1569
2   175990      880          1         846
3   160582     9568          0        1388
4   123400     4000          1         268

In [118]:
#проведем горячее кодирование признака action_id
encoder = ce.OneHotEncoder(cols=['action_id'], use_cat_names=True) # указываем столбец для кодирования
type_bin = encoder.fit_transform(sample_b_prices['action_id'])
sample_b_prices = pd.concat([sample_b_prices, type_bin], axis=1)
sample_b_prices.head()

,user_id,item_id,action_id,item_price,action_id_1.0,action_id_0.0,action_id_2.0
0,118375,4105,1,536,1,0,0
1,107569,8204,1,1569,1,0,0
2,175990,880,1,846,1,0,0
3,160582,9568,0,1388,0,1,0
4,123400,4000,1,268,1,0,0

In [119]:
#создадим сводную таблицу по признаку 'item_id'
b_metrics = sample_b_prices.groupby('item_id')[['action_id_0.0', 'action_id_1.0', 'action_id_2.0']].sum()
b_metrics = pd.merge(b_metrics, item_prices, on=['item_id'], how='left')

In [120]:
#вычислим метрики
b_metrics['ctr'] = b_metrics['action_id_0.0'] / b_metrics['action_id_1.0']
b_metrics['purchase_rate'] = b_metrics['action_id_2.0'] / b_metrics['action_id_1.0']
b_metrics['gmv'] = b_metrics['action_id_2.0'] * b_metrics['item_price']
b_metrics.head()

,item_id,action_id_0.0,action_id_1.0,action_id_2.0,item_price,ctr,purchase_rate,gmv
0,21,152,996,105,452,0.152610,0.105422,47460
1,36,180,996,93,282,0.180723,0.093373,26226
2,39,150,996,115,1746,0.150602,0.115462,200790
3,50,158,996,100,871,0.158635,0.100402,87100
4,64,175,996,94,1479,0.175703,0.094378,139026

Создадим метрики для sample_c

In [121]:
sample_c_prices = pd.merge(sample_c, item_prices, on=['item_id'], how='left')
sample_c_prices.head()

   user_id  item_id  action_id  item_price
0   274623     2863          1        1283
1   265472      343          1        1196
2   242779     6009          0        1184
3   275009     2184          1         225
4   268104     3134          2         162

In [122]:
#проведем горячее кодирование признака action_id
encoder = ce.OneHotEncoder(cols=['action_id'], use_cat_names=True) # указываем столбец для кодирования
type_bin = encoder.fit_transform(sample_c_prices['action_id'])
sample_c_prices = pd.concat([sample_c_prices, type_bin], axis=1)
sample_c_prices.head()

,user_id,item_id,action_id,item_price,action_id_1.0,action_id_0.0,action_id_2.0
0,274623,2863,1,1283,1,0,0
1,265472,343,1,1196,1,0,0
2,242779,6009,0,1184,0,1,0
3,275009,2184,1,225,1,0,0
4,268104,3134,2,162,0,0,1

In [123]:
#создадим сводную таблицу по признаку 'item_id'
c_metrics = sample_c_prices.groupby('item_id')[['action_id_0.0', 'action_id_1.0', 'action_id_2.0']].sum()
c_metrics = pd.merge(c_metrics, item_prices, on=['item_id'], how='left')

In [124]:
#вычислим метрики
c_metrics['ctr'] = c_metrics['action_id_0.0'] / c_metrics['action_id_1.0']
c_metrics['purchase_rate'] = c_metrics['action_id_2.0'] / c_metrics['action_id_1.0']
c_metrics['gmv'] = c_metrics['action_id_2.0'] * c_metrics['item_price']
c_metrics.head()

,item_id,action_id_0.0,action_id_1.0,action_id_2.0,item_price,ctr,purchase_rate,gmv
0,21,215,994,56,452,0.216298,0.056338,25312
1,36,212,993,59,282,0.213494,0.059416,16638
2,39,209,994,54,1746,0.210262,0.054326,94284
3,50,216,994,53,871,0.217304,0.053320,46163
4,64,208,994,78,1479,0.209256,0.078471,115362

Проведем AA-тестирование. Рассмотрим метрики в группах A и С

In [125]:
#установим уровень значимости
alpha = 0.01
#установим показатели для определения типа распределения
H0 = 'Данные распределены нормально'
Ha = 'Данные не распределены нормально (мы отвергаем H0)'

In [126]:
#проведем проверку распределений на нормальность по метрике 'ctr' в сэмпле А
_, p = shapiro(a_metrics['ctr'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.364
Данные распределены нормально

In [127]:
#проведем проверку распределений на нормальность по метрике 'ctr' в сэмпле C
_, p = shapiro(c_metrics['ctr'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.173
Данные распределены нормально

In [128]:
#проведем проверку распределений на нормальность по метрике 'purchase_rate' в сэмпле А
_, p = shapiro(a_metrics['purchase_rate'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.021
Данные распределены нормально

In [129]:
#проведем проверку распределений на нормальность по метрике 'purchase_rate' в сэмпле C
_, p = shapiro(c_metrics['purchase_rate'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.203
Данные распределены нормально

In [130]:
#проведем проверку распределений на нормальность по метрике 'gmv' в сэмпле А
_, p = shapiro(a_metrics['gmv'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.000
Данные не распределены нормально (мы отвергаем H0)

In [131]:
#проведем проверку распределений на нормальность по метрике 'gmv' в сэмпле C
_, p = shapiro(c_metrics['gmv'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.000
Данные не распределены нормально (мы отвергаем H0)

Таким образом, метрики 'ctr' и 'purchase_rate' имеют нормально распределение, а метрика 'gmv' имеет распределение, отличающееся от нормального

Для работы с метриками 'ctr' и 'purchase_rate' воспользуемся двухвыборочным т-критерием

In [132]:
H0 = 'Нет значимой разницы между отношением кликов к просмотрам товаров.'
Ha = 'Есть значимая разница между отношением кликов к просмотрам товаров.'

In [133]:
test_ctr_ac = ttest_ind(a_metrics['ctr'], c_metrics['ctr'], equal_var=True)
alpha = 0.05
p = round(test_ctr_ac[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница между отношением кликов к просмотрам товаров.

In [134]:
print('Среднее значение в колонке по метрике ctr в сэмпле A: {}'.format(a_metrics['ctr'].mean()))
print('Среднее значение в колонке по метрике ctr в сэмпле C: {}'.format(c_metrics['ctr'].mean()))

Среднее значение в колонке по метрике ctr в сэмпле A: 0.20006327420233697
Среднее значение в колонке по метрике ctr в сэмпле C: 0.2099519097313799

In [135]:
H0 = 'Нет значимой разницы между отношением покупок к просмотрам товаров.'
Ha = 'Есть значимая разница между отношением покупок к просмотрам товаров.'

In [136]:
test_purchase_rate_ac = ttest_ind(a_metrics['purchase_rate'], c_metrics['purchase_rate'], equal_var=True)
alpha = 0.05
p = round(test_purchase_rate_ac[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница между отношением покупок к просмотрам товаров.

In [137]:
print('Среднее значение в колонке по метрике purchase_rate в сэмпле A: {}'.format(a_metrics['purchase_rate'].mean()))
print('Среднее значение в колонке по метрике purchase_rate в сэмпле C: {}'.format(c_metrics['purchase_rate'].mean()))

Среднее значение в колонке по метрике purchase_rate в сэмпле A: 0.049950264374079234
Среднее значение в колонке по метрике purchase_rate в сэмпле C: 0.06005222902769245

In [138]:
H0 = 'Нет значимой разницы в оборотах товаров.'
Ha = 'Есть значимая разница в оборотах товаров.'

Для анализа метрики 'gmv' воспользуемся критерием Манна-Уитни

In [139]:
test_gmv_ac = mannwhitneyu(a_metrics['gmv'], c_metrics['gmv'], alternative='two-sided')
alpha = 0.05
p = round(test_gmv_ac[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница в оборотах товаров.

In [140]:
print('Среднее значение в колонке по метрике gmv в сэмпле A: {}'.format(a_metrics['gmv'].mean()))
print('Среднее значение в колонке по метрике gmv в сэмпле C: {}'.format(c_metrics['gmv'].mean()))

Среднее значение в колонке по метрике gmv в сэмпле A: 57671.55
Среднее значение в колонке по метрике gmv в сэмпле C: 69413.8

Поскольку есть значимая разница по всем метрикам в сэмплах А и C (при этом выборка C имеет более высокие значения по всем метрикам), то проводить сравнения между сэмплами A и B - необъективно и рисковано

Проведем AB-тестирование между сэмплами A и B

In [141]:
#установим уровень значимости
alpha = 0.01
#установим показатели для определения типа распределения
H0 = 'Данные распределены нормально'
Ha = 'Данные не распределены нормально (мы отвергаем H0)'

In [142]:
#проведем проверку распределений на нормальность по метрике 'ctr' в сэмпле B
_, p = shapiro(b_metrics['ctr'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.010
Данные распределены нормально

In [143]:
#проведем проверку распределений на нормальность по метрике 'purchase_rate' в сэмпле B
_, p = shapiro(b_metrics['purchase_rate'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.172
Данные распределены нормально

In [144]:
#проведем проверку распределений на нормальность по метрике 'gmv' в сэмпле B
_, p = shapiro(b_metrics['gmv'])
print('p=%.3f' % p)
# Интерпретация 
if p > alpha:
	print(H0)
else:
	print(Ha)

p=0.000
Данные не распределены нормально (мы отвергаем H0)

Получаем данные, которые сходятся с данными в сэмплах A и B

Для анализа метрик 'ctr' и 'purchase_rate' воспользуемся парным т-тестом

In [145]:
H0 = 'Нет значимой разницы между отношением кликов к просмотрам товаров.'
Ha = 'Есть значимая разница между отношением кликов к просмотрам товаров.'

In [146]:
test_ctr_ab = stats.ttest_rel(a_metrics['ctr'], b_metrics['ctr'])
alpha = 0.05
p = round(test_ctr_ab[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница между отношением кликов к просмотрам товаров.

In [147]:
print('Среднее значение в колонке по метрике ctr в сэмпле A: {}'.format(a_metrics['ctr'].mean()))
print('Среднее значение в колонке по метрике ctr в сэмпле B: {}'.format(b_metrics['ctr'].mean()))

Среднее значение в колонке по метрике ctr в сэмпле A: 0.20006327420233697
Среднее значение в колонке по метрике ctr в сэмпле B: 0.15994000020181226

In [148]:
H0 = 'Нет значимой разницы между отношением покупок к просмотрам товаров.'
Ha = 'Есть значимая разница между отношением покупок к просмотрам товаров.'

In [149]:
test_purchase_rate_ab = stats.ttest_rel(a_metrics['purchase_rate'], b_metrics['purchase_rate'])
alpha = 0.05
p = round(test_purchase_rate_ab[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница между отношением покупок к просмотрам товаров.

In [150]:
print('Среднее значение в колонке по метрике purchase_rate в сэмпле A: {}'.format(a_metrics['purchase_rate'].mean()))
print('Среднее значение в колонке по метрике purchase_rate в сэмпле B: {}'.format(b_metrics['purchase_rate'].mean()))

Среднее значение в колонке по метрике purchase_rate в сэмпле A: 0.049950264374079234
Среднее значение в колонке по метрике purchase_rate в сэмпле B: 0.0998753355129059

Для анализа метрики 'gmv' воспользуемся критерием Уилкоксона

In [151]:
H0 = 'Нет значимой разницы в оборотах товаров.'
Ha = 'Есть значимая разница в оборотах товаров.'

In [152]:
test_gmv_ab = stats.wilcoxon(a_metrics['gmv'], b_metrics['gmv'])
alpha = 0.05
p = round(test_gmv_ab[1],2)
if p>alpha:
    print(f"{p} > {alpha}. Мы не можем отвергнуть нулевую гипотезу. {H0}")
else:
    print(f"{p} <= {alpha}. Мы отвергаем нулевую гипотезу. {Ha}")

0.0 <= 0.05. Мы отвергаем нулевую гипотезу. Есть значимая разница в оборотах товаров.

In [153]:
print('Среднее значение в колонке по метрике gmv в сэмпле A: {}'.format(a_metrics['gmv'].mean()))
print('Среднее значение в колонке по метрике gmv в сэмпле B: {}'.format(b_metrics['gmv'].mean()))

Среднее значение в колонке по метрике gmv в сэмпле A: 57671.55
Среднее значение в колонке по метрике gmv в сэмпле B: 115275.006

AB-тестирование дает нам понимание того, что существуют изменения между первичным и вторичным тестированием. Посетители магазина стали меньше просто кликать на товар, но чаще нажимать на кнопку "купить". Значимо вырос и оборот магазина. Изменения в деятельности маркетплейса пошли на ему на пользу.